# Generated by Django 3.0.7 on 2020-07-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='note',
            new_name='item',
        ),
    ]
