# Generated by Django 3.0.7 on 2020-07-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_list_app', '0002_auto_20200710_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default='No Title', max_length=32),
        ),
    ]
