# Generated by Django 3.0.7 on 2020-07-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_list_app', '0003_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(default='No notes', max_length=1023),
        ),
    ]
