# Generated by Django 3.0.7 on 2020-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_list_app', '0004_auto_20200711_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(max_length=1023),
        ),
    ]
