# Generated by Django 3.0.7 on 2020-07-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_list_app', '0005_auto_20200711_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='completed',
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
