# Generated by Django 3.0.7 on 2020-07-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_list_app', '0007_auto_20200711_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='heading',
        ),
    ]
